// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJljnBMtHQk_4OItvUWThaZchLlNmOuw8',
    appId: '1:310558292937:web:269678fa50835b06798618',
    messagingSenderId: '310558292937',
    projectId: 'wori-app-7d380',
    authDomain: 'wori-app-7d380.firebaseapp.com',
    storageBucket: 'wori-app-7d380.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKtIiEHy_3otzFWCNDB-WcuJFiGvGHl-I',
    appId: '1:310558292937:android:c75afa5b5f5410a4798618',
    messagingSenderId: '310558292937',
    projectId: 'wori-app-7d380',
    storageBucket: 'wori-app-7d380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhIgFRa-FGtOSHakGDOYH_XaQaHqkGbKs',
    appId: '1:310558292937:ios:40922dfca5415858798618',
    messagingSenderId: '310558292937',
    projectId: 'wori-app-7d380',
    storageBucket: 'wori-app-7d380.firebasestorage.app',
    iosBundleId: 'com.example.woriApp',
  );
}
